ARG SLURM_VERSION=25.05.3

FROM slurm-docker-cluster:${SLURM_VERSION}

RUN yum -y install openmpi openmpi-devel papi papi-devel gnuplot && yum clean all

ENV PATH=/usr/lib64/openmpi/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH